# TDM 직접구현

### 1. 공백으로 토큰화

In [1]:
docs = ['동물원 코끼리','동물원 원숭이 바나나','엄마 코끼리 아기 코끼리','원숭이 바나나 코끼리 바나나']

In [2]:
doc_1s=[]
for doc in docs:
    doc_1s.append(doc.split(' '))
    
doc_1s    

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

### 2. 토큰 배열화

In [16]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))

for doc in doc_1s:
    for token in doc:
        word2id[token]
        
word2id        

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [17]:
doc_1s

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [18]:
doc

['원숭이', '바나나', '코끼리', '바나나']

In [5]:
import numpy as np

TDM = np.zeros((len(word2id), len(doc_1s)), dtype=int)      #6 by 4
print(TDM)

for i, doc in enumerate(doc_1s):
    for token in doc:
        TDM[word2id[token], i] +=1
        
TDM        

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[1, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [8]:
import pandas as pd

doc_names = ['문서'+ str(i) for i in range(len(doc_1s))]
print('doc_names', doc_names)


sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]

df_TDM = pd. DataFrame(TDM, columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

doc_names ['문서0', '문서1', '문서2', '문서3']


문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0

In [ ]:
## sklearn

In [9]:
docs = ['동물원 코끼리','동물원 원숭이 바나나','엄마 코끼리 아기 코끼리','원숭이 바나나 코끼리 바나나']ㅜ

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 2],
       [0, 2, 0, 0, 1, 1]], dtype=int64)

In [15]:
import pandas as pd

doc_names = ['문서'+ str(i) for i in range(len(doc_1s))]
vocab = count_vect.get_feature_names()
print(vocab)



df_TDM = pd. DataFrame(DTM.toarray().T ,columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

['동물원', '바나나', '아기', '엄마', '원숭이', '코끼리']


문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    0    1    0    2
아기     0    0    1    0
엄마     0    0    1    0
원숭이    0    1    0    1
코끼리    1    0    2    1