# 원핫인코딩 직접 구현

In [2]:
# 인코딩 대산 단어를 담은 리스트

word_1s = ['원숭이','바나나','사과','코끼리']

In [3]:
from collections import defaultdict
import numpy as np


# {단어:인덱스} 사전구축== 딕셔너리를 새로 만든다
# 내가 넣은 단어의 갯수만큼 사전의 길이가 길어진다

word2id_dic = defaultdict(lambda:len(word2id_dic))
word2id_dic

defaultdict(<function __main__.<lambda>()>, {})

In [7]:
# 원숭이, 바나나, 사과, 코끼리가 들어감

for word in word_1s:
    word2id_dic[word]
    
word2id_dic    

defaultdict(<function __main__.<lambda>()>,
            {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})

In [5]:
#고유 단어갯수 : 4개

n_unique_words = len(word2id_dic)
n_unique_words

4

In [6]:
# 원핫 백터를 만들기 위해 비어있는 백터를 생성

one_hot_vectors = np.zeros((len(word_1s), n_unique_words))

one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
# 단어고유 인덱스

for i, word in enumerate(word_1s):
    index = word2id_dic[word]
    one_hot_vectors[i,index] += 1
one_hot_vectors    

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# sklearn

In [39]:
!pip install scikit-learn

In [40]:
word_1s

['원숭이', '바나나', '사과', '코끼리']

In [41]:
# 일단 배열 형태를 바꾼다

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

values = array(word_1s)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [42]:
# 각각의 데이터에 인덱스 부여하기, 컴퓨터 내부적으로 부여하는 것.


label_enc = LabelEncoder()

In [43]:
#가로,세로 바꾸기

int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [45]:
# 원핫인코더 선언
# 기본은 true, false는 array 형태

onehot_enc = OneHotEncoder(sparse=False)

# reshape
int_enc = int_enc.reshape(len(int_enc), 1)
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])