## bow 생성 방법

1. 띄어쓰기로 토큰화
2. 각 토큰에 고유 인덱스 부여
3. 각 인덱스 위치에 토큰 등장 횟수를 기록

In [8]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어','오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [9]:
doc_1s=[]
for doc in docs:
    doc_1s.append(doc.split(' '))
doc_1s    

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [10]:
# 인덱스 부여 + 딕셔너리 형태 변환

from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [11]:
# 중복은 제외,토큰들만 defaultdict 시킨다

for doc in doc_1s:
    for token in doc:
        word2id[token]

word2id        

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [12]:
import numpy as np
BOW_1s=[]
BOW_1s

[]

In [14]:
doc_1s

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [13]:
for i, doc in enumerate(doc_1s):
    bow= np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1
    BOW_1s.append(bow.tolist())

BOW_1s    

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [18]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [19]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)    

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [20]:
for i in range(len(docs)):
    print("문서{}:{}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BOW_1s[i]], columns=vocab))
    print("\n\n")

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1:오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

## 단어의 순서를 고려하지 않은 BOW

### 1. 띄어쓰기로 토큰화

In [23]:
docs2 = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해','나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [24]:
doc_2s=[]
for doc in docs2:
    doc_2s.append(doc.split())
doc_2s    

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

### 2. 각 토큰에 인덱스 부여

In [25]:
# 새로운 딕셔너리를 만들고, word의 길이 만큼 딕셔너리가 생김

from collections import defaultdict
word = defaultdict(lambda : len(word))



# 딕셔너리에 토큰 넣기
for doc in doc_2s:
    for token in doc:
        word[token]

word    


defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [26]:
BOW=[]

for i, doc in enumerate(doc_2s):
    bow= np.zeros(len(word), dtype=int)
    print(bow)
   

    for token in doc:
        bow[word[token]] += 1
    BOW.append(bow.tolist())

BOW

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [29]:
sorted_vocab2 = sorted((value, key) for key, value in word.items())
print('sorted_vocab', sorted_vocab2)

sorted_vocab [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [30]:
vocab2=[]
for v in sorted_vocab2:
    vocab2.append(v[1])
print('vocab',vocab2) 

vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']


### 토큰 등장 횟수 기록

In [31]:
for i in range(len(docs)):
    print("문서{}:{}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BOW[i]], columns=vocab2))
    print("\n\n")

문서0:나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1:나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1